// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL1qvKLOfAHNpFM1l9yng1RudIqCcLeV4',
    appId: '1:965812404674:web:40d09604738c8956b2565b',
    messagingSenderId: '965812404674',
    projectId: 'skripsi-fd446',
    authDomain: 'skripsi-fd446.firebaseapp.com',
    storageBucket: 'skripsi-fd446.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAshscEIlVxeESCGm3-b0E81qGtk6g4WiY',
    appId: '1:965812404674:android:961135bfb4b01234b2565b',
    messagingSenderId: '965812404674',
    projectId: 'skripsi-fd446',
    storageBucket: 'skripsi-fd446.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKbQJLzGiN4c2XBiC9CeghC2EI_jmB94Q',
    appId: '1:965812404674:ios:f426d7808b351a7eb2565b',
    messagingSenderId: '965812404674',
    projectId: 'skripsi-fd446',
    storageBucket: 'skripsi-fd446.appspot.com',
    iosBundleId: 'com.example.skripsi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKbQJLzGiN4c2XBiC9CeghC2EI_jmB94Q',
    appId: '1:965812404674:ios:f426d7808b351a7eb2565b',
    messagingSenderId: '965812404674',
    projectId: 'skripsi-fd446',
    storageBucket: 'skripsi-fd446.appspot.com',
    iosBundleId: 'com.example.skripsi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL1qvKLOfAHNpFM1l9yng1RudIqCcLeV4',
    appId: '1:965812404674:web:9351451d0bb78158b2565b',
    messagingSenderId: '965812404674',
    projectId: 'skripsi-fd446',
    authDomain: 'skripsi-fd446.firebaseapp.com',
    storageBucket: 'skripsi-fd446.appspot.com',
  );
}
